#importamos la imagen base de python
FROM python:3.12-slim

#Crear carpeta de trabajo
WORKDIR /app

#Copiar requerimientos
COPY requirements.txt .

#Instalar requerimienros dentro del contenedor
RUN pip install --no-cache-dir -r requirements.txt

#copiar archivo del API
COPY ./app ./app

#Exponer puerto
EXPOSE 8000

#Comando para ejecutar FASTAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]